<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTCTb1CN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTCTb1CN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTCTb1CN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTCTb1CN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTCTb1CN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TCTb1CN',
    'container.build_id' => '896c3c01',
    'container.build_time' => 1594727432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTCTb1CN');
